### ISSUE TITLE
[Opinião] Tradução de trechos de código. Sim ou não?

### ISSUE THREAD

**Issue by cezaraugusto** [cez-aug/You-Dont-Know-JS#108]
Queria saber a opinião de vocês se devemos ou não traduzir os trechos de código apresentados no livro. Se possível, o motivo da opinião.

No início optei por **não**, pois o primeiro livro continha muitas demonstrações utilizando imagens com o resultado do código. O modelo não acompanhou os outros títulos até onde eu sei. 

Se forem casos isolados, acho que vale a pena _transformar_ a imagem para reproduzir o conteúdo em Português.

**Comment by gmsecrieru** [comment]
Eu acho válido traduzirmos em casos [como este](https://github.com/cezaraugusto/You-Dont-Know-JS/pull/107/commits/23c0e0e9b96ad54e3357377e43e0a92b26e4bbb0#diff-bd5b8a738e27479e4c7d722434a0c05dL65), onde o nome das funções aparece diversas vezes no texto para descrever o que está acontecendo. 

Sei que pode soar meio conveniente defender um argumento usando um exemplo de conteúdo que eu traduzi, mas minha intenção na verdade é expôr o que me ocorreu na hora: se o leitor não tem conhecimento da lingua inglesa, `doSomething` e/ou `doSomethingElse` tornam-se termos que podem causar "fricção" na leitura (e.g. "O que isso significa? Será relevante pro conteúdo? Vou pesquisar..."). Enfim, um detalhe de UX ;)

Sobre as imagens, será que o Kyle não possui alguma versão editável para nos disponibilizar?

**Comment by cezaraugusto** [comment]
Na verdade a ideia de traduzir código veio do seu commit mesmo 😁. Eu gostei e tive essa ideia no início, mas abandonei por conta das imagens. Vou falar com o autor pra ver se ele pode nos passar e/ou autorizar a alteração. Seria ótimo.

**Comment by gabsprates** [comment]
Concordo plenamente com vocês.

**Comment by cezaraugusto** [comment]
Conversei com o autor. Dando um alô pra vocês pelo Telegram. Vamos seguir conforme o WORDREFERENCE original

**Comment by gabsprates** [comment]
@cezaraugusto e @gmsecrieru, como vão ficar os trechos de código do **Capítulo 3** do **Scope & Closure**, que foram traduzidos?
