### ISSUE TITLE
Padrões de tradução

### ISSUE THREAD

**Issue by gabsprates** [cez-aug/You-Dont-Know-JS#121]
Gostaria de saber a opinião de vocês para uma questão. Seguinte, alguns usam o arquivo com o nome original, outros renomeiam; uns mantem o parágrafo original e o traduzido pra depois limpar o arquivo, outros vão tirando o texto original e substituindo para a tradução, e assim vai.

Daí me veio a dúvida, seria legal adotarmos um padrão para tratar os arquivos que estão sendo traduzidos?

**Comment by cezaraugusto** [comment]
Acho que desde que nao influencie no resultado final, fica a criterio do tradutor. Eu reviso vendo a versao do tradutor e o diff da versao em ingles (changes from all commits).

Mas nao sei se consegui entender a proposta.

/cc @gmsecrieru

**Comment by gmsecrieru** [comment]
Tenho seguido (meio sumido ultimamente na verdade :grin:) um formato parecido com o do @cezaraugusto e não cheguei a renomear arquivos.

Em relação ao conteúdo, eu particularmente acho mais legal a ideia de ter um arquivo parcialmente traduzido _sem_ conteúdo "duplicado", ou seja, o que foi traduzido é removido 👍

**Comment by gabsprates** [comment]
Acho que dá pra fechar essa. Se alguém tiver mais alguma ideia sobre o assunto, é só abrir de novo. :wink:
