### ISSUE TITLE
Falta de tradução no README.md

### ISSUE THREAD

**Issue by felipe-augusto** [cez-aug/You-Dont-Know-JS#128]
No README.md na seção dos títulos da série faltou substituir a linha:

`Leia online (grátis!): "ES6 & Beyond", Publicado: Compre agora (inglês)`

Por:

`Leia online (grátis!): "ES6 & Além", Publicado: Compre agora (inglês)`

Ia abrir uma PR, mas meu fork está atrás e estou em outro PC, se quiser posso arrumar isso mais tarde.

**Comment by gabsprates** [comment]
Beleza! Fique à vontade.
