### ISSUE TITLE
Qual seria a melhor tradução para o termo well-formed ?

### ISSUE THREAD

**Issue by MacgyverMartins** [cez-aug/You-Dont-Know-JS#150]
Estou traduzindo o parte de Tipos e Gramática, e surgiu a dúvida de qual seria a melhor tradução para o termo **well-formed**

O contexto da frase é o seguinte:
`The grammar for JavaScript is a structured way to describe how the syntax (operators, keywords, etc.) fits together into well-formed`

**Comment by ViltonBonifacio** [comment]
Olá, @MacgyverMartins . Como o texto é da área de computação, acho que poderia ser algo como **de acordo com as regras de sintaxe**, **sintaxe correta**, **gramática correta**, etc. Fiz essa tradução livre com base na definição dada pelo _The Free Dictionary_.
Apesar disso, o Linguee e o Google Tradutor trouxeram uma definição de **bem formado**. Não sei se seria a mais adequada.

----

Definição sugerida pelo _The Free Dictionary_:
>well-formed 
>
>adj
>1. (Logic) logic linguistics (of a formula, expression, etc) constructed in accordance with the syntactic rules of a particular system; grammatically correct
>
>well′-formed′ 
>adj.
>1. rightly or pleasingly formed: a well-formed contour.
>2. (of an utterance) conforming to the rules of a language; grammatical.

http://www.thefreedictionary.com/well-formed

O Linguee e Google Tradutor:
http://www.linguee.com.br/ingles-portugues/traducao/well-formed.html
https://translate.google.com/?hl=pt#en/pt/well-formed

-----
Não tenho certeza se a minha sugestão está correta. Espero ter ajudado.

**Comment by gmsecrieru** [comment]
Ao ler a frase original (`The grammar for JavaScript is a structured way to describe how the syntax (operators, keywords, etc.) fits together into well-formed, valid programs`) pensei em "... descreve como a sintaxe se encaixa/transforma/possibilita [a escrita/criação de] programas válidos e **coesos**"

**Comment by MacgyverMartins** [comment]
Valeu gente :)
