### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by getify** [cez-aug/You-Dont-Know-JS#154]
I'm glad to see this effort to translate the book series into Portugese. Since I don't speak the language, I'm not sure if the work is complete or not.

For more info about policies around translations of YDKJS, please check these issues: https://github.com/getify/You-Dont-Know-JS/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3A%22foreign%20language%20translations%22%20

In those threads you'll see described the preferred process for how foreign language translations should be handled. It's fine that the work is done on this separate repo, but once the translation is complete, the process then is:

1. file an issue on the main repo to have a branch created for the translation
2. send a PR to have the translation moved into that branch.
3. At that point, the branch on the main repo becomes the "official" repo for the translation. I will add you as a collaborator so you can manage commits there.

**Comment by cezaraugusto** [comment]
Hi Kyle, this is still a work in progress, with 2/6 books translated. It was made in a separated repo just for convenience, as I don't have permissions to the base repo.

In https://github.com/getify/You-Dont-Know-JS/issues/9#issuecomment-37836191 you mentioned that you're willing to _grant specific permission for people to translate the material from [your] repo_, so if you prefer going this way, once I'm allowed to I can move the translation and keep the work from there.

If it's fine to keep the work here until it's done, be certain that I'll ping you asking to move the translation once ready. This was the original plan from the start.

**Comment by getify** [comment]
Yeah it's preferred to keep it here until done then merge. Thanks!
