### ISSUE TITLE
O capítulo 2 da série "this e objects prototypes" tem um trecho em inglês

### ISSUE THREAD

**Issue by tdias25** [cez-aug/You-Dont-Know-JS#288]
O capítulo 2 da série "this e objects prototypes" tem um trecho em inglês.

você pode localizar ele em:

"While arrow-functions provide an alternative to using bind(..) on a function to ensure its this, which can seem attractive, it's important to note that they ess"

e logo depois tem o mesmo trecho já traduzido

**Comment by cezaraugusto** [comment]
obrigado por sinalizar @tdias25. poderia abrir um PR para corrigir?

**Comment by tdias25** [comment]
Beleza, faço essa semana ;)

**Comment by gabsprates** [comment]
@tdias25, chegou a mandar o PR? Podemos fechar a issue?

**Comment by Ilivanilton** [comment]
olá @gabsprates , a #303  é referente a esta issue. Falta aceitação.
Att.

**Comment by cezaraugusto** [comment]
aprovado https://github.com/cezaraugusto/You-Dont-Know-JS/pull/303, fechando. obrigado turma!
