### ISSUE TITLE
Dúvida sobre os títulos dos livros

### ISSUE THREAD

**Issue by idrodrigosantos** [cez-aug/You-Dont-Know-JS#296]
No [README ](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/README.md#you-dont-know-js-s%C3%A9rie-de-livros) do repositório e nas capas dos livros, os títulos estão usando "&", já no [WORDREFERENCE ](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md#títulos) os títulos estão usando "E", exceto "this & Prototipagem de Objetos".
Gostaria de saber qual deve ser usado, para eu poder corrigir.

**Comment by cezaraugusto** [comment]
Oi @imsantosrodrigo, vamos nessa. O correto é o & (E comercial). Se puder enviar um PR corrigindo o erro ia ser 💯.

**Comment by idrodrigosantos** [comment]
Ok, irei alterar e fazer um PR
