### ISSUE TITLE
Bug's nos links do arquivo  WORDREFERENCE.md

### ISSUE THREAD

**Issue by Ilivanilton** [cez-aug/You-Dont-Know-JS#306]
Os links "Referências","Títulos" e "Jargões de Programação" não funcionam em:
[WORDREFERENCE](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md) 
 PR #305

**Comment by cezaraugusto** [comment]
closed by https://github.com/cezaraugusto/You-Dont-Know-JS/pull/305
