### ISSUE TITLE
Evangelismo do Projeto

### ISSUE THREAD

**Issue by christyanbrayan** [cez-aug/You-Dont-Know-JS#329]
Olá, gostaria de contribuir, a princípio, com o evangelismo do projeto.

Adicionando esse projeto em repositórios de compartilhamento e divulgação de projetos open source brasileiros que existem por aí, por exemplo. Como esse [aqui](https://github.com/camilatigre/listamaravilhosaopensource). Além de, claro, divulgar via comentários no YouTube (forma como cheguei aqui) e em outras redes.

Aí, desde que concordem na adição do link deste projeto nos repositórios citados e em outros similares, gostaria de saber se, por exemplo, ao adicionar em um e divulgar o link aqui, seria eu já adicionado no hall do contributors.md com a convenção :loudspeaker: Evangelismo do Projeto?

**Comment by victorpothin** [comment]
Olá!

Acredito que esse projeto precise bastante de ajuda para a disseminação dessa leitura, acredito que com o seu empenho e envagelismo, podemos avançar cada vez mais para um repositório com bastante ajuda e esforço de todas as partes envolvidas.

Gostaria de uma reflexão em cima dos proximos pontos.
>Desde a publicação quais medidas foram tomadas para o compartilhamento do repositório.
>O Engajamento proposto via Youtube seria disseminado de via spam.
>Qual outra maneira de compartilhamento poderia ser proposto para alcançar pessoas novas.
