### ISSUE TITLE
Paginação no livro em formato markdown

### ISSUE THREAD

**Issue by matheusfelipeog** [cez-aug/You-Dont-Know-JS#330]
O que acham de implementar uma especie de paginação no final do capítulo de todos os livros em formato markdown? 

**Por que?** Acredito que irá facilitar a leitura e deixar mais fluida sempre que acabar o capitulo de um dos livros.

**Como?** Algo parecido com isso no final de todos capítulos, seguindo o formato md do github:
```markdown
<div align='center'>
<a href="PATH">Anterior</a> | <a href="PATH">Próximo</a>
</div>
```
*Que ficaria assim:*
<div align="center">
<a href="https://github.com/cezaraugusto/You-Dont-Know-JS">Anterior</a> | <a href="https://github.com/cezaraugusto/You-Dont-Know-JS">Próximo</a>
</div>

E no final de cada livro teria o link para o próximo livro e assim por diante.

**Comment by RodrigoCh99** [comment]
ótima idéia! apóio

**Comment by christyanbrayan** [comment]
Achei interessante também. Se aceitarem gostaria de ajudar, caso precise.

**Comment by gabsprates** [comment]
Olá @matheusfelipeog,

Essa é realmente uma boa ideia, no entanto, um dos objetivos é que, quando terminarmos a tradução, façamos um merge desse fork com o projeto principal, do Kyle Simpson. Nesse caso, sai um pouco do escopo da tradução e estaríamos alterando o conteúdo mesmo.

Por isso, acredito que é melhor não adotarmos esse padrão.

De qualquer forma, obrigado 😉
