### ISSUE TITLE
Envio de blocos pequenos para tradução

### ISSUE THREAD

**Issue by cezaraugusto** [cez-aug/You-Dont-Know-JS#68]
Pessoal, 

Como a divisão das traduções está sendo feita em Capítulos, e eles são bem extensos, acho que o melhor caminho é enviar uma PR para cada cabeçalho. Eu estou seguindo esse modelo também. Exemplo:

``` sh
# You Don't Know JS: ES6 & Beyond
# Chapter 8: Beyond ES6

...  (Pull Request Nr 1)


## Async functions

... (Pull Request Nr 2)


### Caveats

... (Pull Request Nr 3)


## Object.observe(..)

... (Pull Request Nr 4)


### Custom Change Events

... (Pull Request Nr 5)


```

O objetivo de fazer essa divisão de _módulos_ é para facilitar a revisão dos trabalhos que estamos fazendo e disponiblizar de forma mais fluida ao público que não traduz, mas lê o livro e pode contribuir com o trabalho. 

Pensei em colocar uma divisão (`<hr>`) na parte onde a tradução foi interrompida, mas não estou certo disso. Meu motivo é que isso ajudaria a dividir o conteúdo traduzido/não traduzido a quem está lendo. O que acham?

/cc @gabsprates @ebragaparah @robsongomes @vlacerda @diegofaria @andrediasgustavo @nersoh @PedroFelipe

**Comment by gabsprates** [comment]
@cezaraugusto sim, concordo, eu até estou mandando commits desses blocos pensando nisso, mas não fiz pull request de nenhum ainda.
Concordo com a ideia.

**Comment by andrediasgustavo** [comment]
Boa, vou fazer dessa maneira assim agiliza o processo.

**Comment by raribeiro** [comment]
Concordo, @cezaraugusto !
