### ISSUE TITLE
Comunicação

### ISSUE THREAD

**Issue by gabsprates** [cez-aug/You-Dont-Know-JS#70]
Gostaria da opinião de vocês.
Seria necessário um grupo no Slack só para este projeto?

**Comment by raribeiro** [comment]
Um grupo no Slack seria bem interessante, mas acredito que um grupo dentro de um canal já conhecido traria mais visibilidade para o projeto e consequentemente mais membros.

**Comment by cezaraugusto** [comment]
Acho legal um canal pra todo mundo se conhecer e definir o progresso/rotas do projeto. Não tenho uma opinião formada sobre o melhor meio, queria saber da turma. 

/cc @nathaliabruno @gustavoteodoro @ebragaparah @robsongomes @vlacerda @diegofaria @andrediasgustavo @nersoh @nelsonpjunior @PedroFelipe (esqueci alguém??)

**Comment by nelsonpjunior** [comment]
Eu acho que um grupo no slack seria legal, mas talvez um grupo no facebook tenha um pouco mais de visibilidade.

**Comment by gabsprates** [comment]
@nelsonpjunior @cezaraugusto @raribeiro Acho o grupo no Slack seria bom não só para a tradução e revisão do projeto, mas para dúvidas gerais sobre JS, porque se ficasse com o foco na tradução em si, as Issues resolvem isso. Talvez no Facebook realmente seja bom pela visibilidade @nelsonpjunior e também poderia servir para dúvidas como falei.

**Comment by raribeiro** [comment]
@gabsprates além de concordar, posso concluir. Acredito que o Slack possa ajudar na questão da comunicação, os grupos do Facebook são muito engessados para comunicação em realtime.

**Comment by robsongomes** [comment]
Acho que seria excelente a criação de um grupo no slack. Eu tenho dificuldade em traduzir alguns termos e acho que no grupo a gente resolveria esse tipo de dúvida de forma bem rápida. Além de a interação ser muito boa.

**Comment by gabsprates** [comment]
Legal então. O que acham de **YDKJS_BR**?
É feio kkk
Alguém tem alguma sugestão?

**Comment by robsongomes** [comment]
SabeDeNadaInocente_JS :P #kidding

**Comment by cezaraugusto** [comment]
"We Don't Know JS"?

**Comment by gabsprates** [comment]
boas sugestões kkkk
mas eu falo pro **nome_do_grupo**.slack.com

**Comment by robsongomes** [comment]
acho que ydkjs_br tá bom... é curto e objetivo ou ainda ykdjs_to_br precisa ser bonito não hehe

**Comment by raribeiro** [comment]
Gosto bastante de **ydkjs_br.slack.com**.

**Comment by gabsprates** [comment]
É o seguinte, só são permitidos números, traços e letras, daí ficou **ydkjsbr.slack.com**, blz?
~~https://gabsprates.typeform.com/to/LkSNWq~~
Tá aqui o link para cadastro, acho que seria bom colocar no `README.md`, que tal?

EDITADO:
O grupo do Slack não funcionará mais, foquemos no [Telegram](https://telegram.me/joinchat/BwXy1AhgwF-pbk0OvIdaxA).

**Comment by woliveiras** [comment]
Galera, desculpem me envolver, mas já me envolvendo, o @raribeiro [comentou](https://github.com/cezaraugusto/You-Dont-Know-JS/issues/70#issuecomment-217634045) sobre entrarem em um Slack já existente e criarem um canal, acho mais interessante pra envolver mais as comunidades aqui no projeto.
Tem o da BrazilJS, o do ABC-DEV que é aberto pro mundo (não só pra galera do Grande ABC Paulista) e o do Front End Brasil, que são grupos que falam muito sobre JavaScript.

**UPDATE**

Tem o da Nodejs Brasil também.

**Comment by woliveiras** [comment]
Existem muitos grupos no Slack e a gente fica com tantas abas abertas no APP que até trava! kkkk

**Comment by cezaraugusto** [comment]
Amigos, qual a finalidade da criação dessa comunicação pra vocês? Fiquei em dúvida.
- Grupo para comunicação entre as partes que querem contribuir ou contribuem com projeto
- Grupo para discussão geral sobre JS
- Grupo de troca de informações e aprendizado coletivo

**Comment by gabsprates** [comment]
Na minha opinião, o grupo seria para discussões gerais sobre JS, e troca de informações e aprendizado, porque comunicar sobre as partes do livro, fazemos isso aqui no próprio GitHub.

**Comment by raribeiro** [comment]
@cezaraugusto concordo com o @gabsprates, mas acho que seria melhor um canal para bater papo corrente sobre itens do próprio livro, pois nem sempre uma pergunta do tipo: "@fulano, você entendeu essa parte aqui? Acho que minha interpretação da explicação é outra..." seria elegível para toda uma burocracia de uma _issue_. 

Mas complementando, se for um canal apenas para falar sobre JS e troca de informações @gabsprates, acho melhor todo mundo ficar em um canal já existente, até porque também vai movimentar o projeto. São só ideias, mas as deixo aqui para chegarmos em um consenso em breve.

@cezaraugusto e demais, me desculpem o sumiço essa semana, mas foi uma semana conturbada. Amanhã volto com as minhas correções e traduções.

**Comment by cezaraugusto** [comment]
@raribeiro concordo e acho acho que as suas ideias cumprem a finalidade. +1

Sobre os meios, acho o slack meio _overkill_ pra finalidade de debater _sobre o livro_. Pensei em algo mais reduzido (entretanto, meu voto nesse ponto vai com a maioria). A @nathaliabruno (que corrige todas as minhas cagadas em português) me falou sobre o Telegram, queria saber a opinião de vocês, e em especial a do @gabsprates que tomou a iniciativa e pra mim tem um peso maior sobre a decisão.

@raribeiro conversei com alguns sobre um outro grupo que pensei em abrir, sobre opensource, pelo Twitter. Se for ativo lá me dá um ping (meu DM aberto, usuário é o mesmo daqui), queria saber sua opinião também.

**Comment by gabsprates** [comment]
Concordo @raribeiro, é melhor mesmo. Eu tive a ideia de fazer um grupo o para discussões, como falei, mas realmente, já existem vários grupos que atendem essa finalidade, então é melhor não. A ideia do @cezaraugusto, de usar o Telegram, é uma boa ideia. Eu uso Telegram e é bacana pra comunicar.

Então, fechamos em criar um grupo no Telegram?

**Comment by raribeiro** [comment]
@cezaraugusto e @gabsprates por mim telegram fechado :+1: Uso ele com alguns amigos e participo de alguns grupos também. 

@cezaraugusto te mando um ping, sou bem ativo no twitter também. Adoraria saber mais detalhes sobre o open source, até por estar bastante envolvido com alguns estudos na área marketing e segurança. 

Preciso começar a me aproximar mais de vocês e da comunidade porque estou começando a não dar mais conta do trabalho e é hora de começar buscar os melhores para podermos crescer juntos :+1:

**Comment by raribeiro** [comment]
@gabsprates você cuida da criação?

**Comment by gabsprates** [comment]
@raribeiro crio sim, na verdade, tá aqui o [link](https://telegram.me/joinchat/BwXy1AhgwF-pbk0OvIdaxA)

**Comment by cezaraugusto** [comment]
Vou fazer a ref no README e deixar a issue aberta ate propagar.

**Comment by raribeiro** [comment]
blz @cezaraugusto ! Thanks @gabsprates ! Show de bola!

**Comment by cezaraugusto** [comment]
Pessoal, após 25 dias aberta, fechando a issue.
