### ISSUE TITLE
Substituição do termo "Encerramento" por "Clausura" (ou Closure)

### ISSUE THREAD

**Issue by gmsecrieru** [cez-aug/You-Dont-Know-JS#91]
Olá, pessoal!

Primeiramente, meus parabéns pelo trabalho. Há tempos pensava que esta tradução seria muito útil para a comunidade de língua portuguesa e fiquei bem feliz quando vi que já estava em andamento! 

Com a ideia de contribuir para o projeto, dei uma olhada geral nas issues e no conteúdo já feito e percebi uma questão que me parece bem relevante: a adoção do termo [Encerramento](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md#c) em vez de [Clausura](https://pt.wikipedia.org/wiki/Clausura_%28ci%C3%AAncia_da_computa%C3%A7%C3%A3o%29), ou até mesmo a manutenção de _Closure_, visto que não só trata-se de um mecanismo crucial para o entendimento do funcionamento da linguagem, mas também pode facilitar a pesquisa aprofundada neste assunto e a compreensão do texto para leitores oriundos de outras linguagens de programação que compartilham deste conceito. 

EDIT: Vi que o assunto já passou pela issue #19, mas acredito que a utilização do termo "encerramento" em algumas das fontes citadas também se trata de um equívoco, visto que a própria definição deste conceito está mais próxima de "algo que _envolve_ outra coisa" do que do ato ou efeito de encerrar. Fiquem a vontade pra fechar a issue, mas fico à disposição para [revisar o conteúdo](https://github.com/cezaraugusto/You-Dont-Know-JS/search?utf8=%E2%9C%93&q=encerramento) se julgarem a troca útil :)

**Comment by gabsprates** [comment]
:+1:

**Comment by cezaraugusto** [comment]
@gmsecrieru muito válida sua proposta.

O objetivo é realmente atender ao maior público possível e deixar clara a tradução, e seus argumentos foram muito válidos, apontando para o uso comum da palavra por outras didáticas e linguagens. 

Estava me guiando por livros já traduzidos (que referenciam como _encerramentos_), e pelo MSDN (se não me engano, dita como _fechamento_). A ideia de _algo que envolve_ realmente incorpora o espírito de _closure_, e se _clausura_ se encaixa no perfil, então que seja a palavra adotada.

+1 pra sua ideia e ficaria muito feliz com a sua ajuda.

**Comment by raribeiro** [comment]
:+1: @gmsecrieru

**Comment by gabsprates** [comment]
Então ficou definido que _closure_ será traduzido para **clausura**, certo?

**Comment by gmsecrieru** [comment]
👍  Acho até que podemos fechar essa issue né? Já está no `WORDREFERENCE`, vou atualizar o título das issues dos capítulos ;)

**Comment by gabsprates** [comment]
Creio que já dá pra fechar definitivamente.

**Comment by gabsprates** [comment]
Galera, sei que já fechamos essa issue e já discutimos o assunto, mas eu gostaria rever este ponto.

Estou cuidando do [capítulo 5 do Scope & Closures](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/scope %26 closures/ch5.md), e é muito estranho colocar **clausura** (**fechamento** seria mais ainda), no lugar de _closure_. Acredito que pelo costume de ver muito conteúdo - mesmo brasileiro - com a expressão original, sejam artigos, palestras ou aulas, e começo a pensar se não estaríamos dificultando as coisas aqui.

É fato que a maioria do conteúdo sobre JavaScript é em inglês. Talvez fosse mais interessante que já introduzíssemos as expressões mais comuns para os leitores, ao invés de traduzi-las e dificultar um pouco a busca por mais conteúdo relacionado.

Estou pensando sobre isso e achei que deveria compartilhar com vocês, o que acham?

**Comment by gmsecrieru** [comment]
@gabsprates a manutenção do termo _Closure_ foi um ponto que eu trouxe na abertura da issue, acho super válido! 👍

**Comment by gabsprates** [comment]
@cezaraugusto e @nathaliabruno, o que acham?

**Comment by cezaraugusto** [comment]
Eu escrevi antes mas de alguma forma não enviou (ei?)

+1 @gabsprates. Mantendo o termo coeso ao longo do livro, estou de acordo com a sua proposta.

**Comment by ViltonBonifacio** [comment]
Olá. Caso a decisão final tenha sido por adotar _`closure`_, peço a gentileza atualizem o _wordreference_, pois me causou um pouco de dúvida na hora de revisar. Se for mais conveniente para o grupo, posso abrir a PR após a confirmação.

**Comment by gmsecrieru** [comment]
@ViltonBonifacio pode enviar uma PR com a alteração, obrigado!

**Comment by gmsecrieru** [comment]
Encerrada via #144
